### PR TITLE
replacing openapi.json for discover & use web apis with power apps

### PR DESCRIPTION
**Pull request by codemillmatt**
issue discovered w/ some sample code - updating it with this PR.

### CODE REVIEW

**Review by z824617 — APPROVED** [review]

**Comment by codemillmatt** [comment]
This is ready to merge in - @justinyoo - who should I talk to about that?

**Comment by justinyoo** [comment]
@DaveBeasley Could you please merge this change?

**Comment by justinyoo** [comment]
Oh I think I can do that?

**Comment by justinyoo** [comment]
Merged!

**Pull request merged**
